# Generated by Django 2.2 on 2021-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
